/*
 * This source file was generated by the Gradle 'init' task
 */
package se.example;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import java.util.List;
import se.group32.domain.*;

class ciTest {
    @Test void productShouldShowName() {
        // ARRANGE
        Material m = new Material(1, "Plast");
        Material mat = new Material(2, "Metal");
        Product product = new Product(1, "Bottle", 5, List.of(m, mat));

        // ACT
        String result = product.getName();

        // ASSERT
        assertEquals("Bottle", result);
    }

}
