/*
 * This source file was generated by the Gradle 'init' task
 */
package se.example;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        System.out.println("Youre in AppTest");
    }
}
