/*
 * This source file was generated by the Gradle 'init' task
 */
package se.example;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.util.ArrayList;
import java.util.List;

import se.group32.presentation.*;
import se.group32.application.*;
import se.group32.domain.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class ProductTest {
    Product product;

    //Commonly used, only needs to be changed in one spot now
    @BeforeEach
    void setupProduct(){
        // Arrange
        Material plastic = new Material(1, "Plastic", 10.0, Recyclability.Medium);
        Material glass  = new Material(2, "Glass", 5.0, Recyclability.High);

        // Act
        product = new Product(1, "Bottle", 5, List.of(plastic, glass));
    }

    @Test
    void addProductShouldBeCreated() {
        // Assert
        assertNotNull(product);
    }

    @Test
    void shouldGetNameWhenAskingForProductsName() {
        String productName = product.getName();

        // Assert
        assertEquals("Bottle", productName);
    }

    @Test
    void shouldGetIdWhenAskingForProductID(){
        int productId = product.getId();

        // Assert // Act
        assertEquals(1, productId);
    }

    @Test
    void shouldGetSameMaterialWhenAskingForProductMaterial(){
        // Arrange
        Material plastic = new Material(1, "Plastic", 10.0, Recyclability.High);
        Product bottle = new Product(1, "Bottle", 5, List.of(plastic));

        // Assert // Act
        Material material = bottle.getMaterials().get(0);
        assertSame(plastic, material);
    }

    @Test
    void shouldGetLifespanWhenAskingForProductLifespan(){
        int lifespan = product.getLifespan();
        // Assert // Act
        assertEquals(5, lifespan);
    }
}
