/*
 * This source file was generated by the Gradle 'init' task
 */
package se.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.List;

import se.group32.presentation.*;
import se.group32.application.*;
import se.group32.domain.*;

import org.junit.jupiter.api.Test;

class ProductTest {
    @Test
    void addProductShouldBeCreated() {
        // Arrange
        Material plastic = new Material(1, "Plastic");
        Material glass  = new Material(2, "Glass");

        // Act
        Product bottle = new Product(1, "Bottle", 5, List.of(plastic, glass));

        // Assert
        assertNotNull(bottle);
    }

    @Test
    void shouldGetNameWhenAskingForProductsName() {
        // Arrange
        Material plastic = new Material(1, "Plastic");
        Material glass  = new Material(2, "Glass");
        Product bottle = new Product(1, "Bottle", 5, List.of(plastic, glass));

        // Act
        bottle.getName();

        // Assert
        assertEquals("Bottle", bottle.getName());
    }
}
