@startuml Grupp32

'comment
'<|-- inheritence
'*-- composition
'o-- aggregation
'--> uses(or dependency)

Title TRASHMAN(Terrific and Right Application for Swedish Humans Managing Avfall Now)


class MainMenu{
    'Motverka DIP
    -OutputFormatter OutputFormatter
    -ProductManager productManager
    -MaterialManager materialManager
    -handleInput(String choice)
    -printMenu()
    +run()
}

class ProductMenu{
    +run()
    -printMenu()
    -createProduct()
    -listProduct()
    -calculateImpact()
    -showRecyclingGuidance()
}

class MaterialMenu{
    +run()
    -printMenu()
}

class ReportMenu{
    -ProductManager productManager
    -MaterialManager materialManager
    -RecyclingGuidence recyclingGuidence
    +impactCalculation(int choice)
    +showGuidance(int choice)
    +showMaterialImpact(int choice)
}

interface MenuInterface{
    +run()
    -printMenu()
}

class MaterialManager{
    -Material[] materials
    +listMaterial()
}

class Material{
    -String name
    -int impactValue
    -RecyclingCategory recyclingCategory
}

class Product{
    -String name
    -Material[] materials
    -int lifespan
    -String category
    '+Product()
}

interface ImpactCalculationStrategy{
    +calculateImpact(Product product)
}


class RecyclingGuidence{
    +isProductRecyclable(Product product)
    +isMaterialRecyclable(Material material)
}


class SimpleSumStrategy{
    +calculateImpact(Product product)
}

class WeightedByLifespanStrategy{
    +calculateImpact(Product product)
}

class ProductManager{
    -Product[] products
    +createProduct()
    +listProducts()
    +getDetails()
    +calculateImpact(Product product)
}

class InputValidator{
    +ValidateInt(String string):boolean
}

enum RecyclingCategory{
    {PLASTIC, PAPER, METAL}
}

'Main "1" o-- "1" MainMenu
MenuInterface <-- MainMenu
MainMenu *-- MaterialMenu
MainMenu *-- ProductMenu
ProductMenu *-- ReportMenu
MaterialMenu *-- ReportMenu
MenuInterface <-- MaterialMenu
MenuInterface <-- ProductMenu
ReportMenu "1" o-- "1" ProductManager
ReportMenu "1" o-- "1" MaterialManager
MaterialManager o-- RecyclingGuidence
ProductManager o-- RecyclingGuidence
ProductManager "1" --> "many" Product
ProductMenu o-- ProductManager
ProductMenu --> InputValidator
ProductManager --> ImpactCalculationStrategy
Product "1" *-- "many" Material
Material *-- RecyclingCategory
MaterialMenu --> InputValidator

ImpactCalculationStrategy <-- WeightedByLifespanStrategy
ImpactCalculationStrategy <-- SimpleSumStrategy
